---
title: "syntactic_Agreement_measure"
output: html_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Measuring Verbal Person Agreement for all 18 Languages

```{r message=FALSE, warning=FALSE, results='hide'}
#loading multicastR package
library(multicastR)

#loading data.table (like tidyverse but faster)
library(data.table)

#get all corpus data
mc <- multicast()
mc <- as.data.table(mc)
```

#### Algorithm to Add Clause ID Column to MC Data* 

```{r results='hide'}
# 1. add row indices to the table (for sorting)
mc[, I := .I]

# 2. create a subset containing only clause boundary markers (<##>, <#>, <%>)
y <- mc[grepl("^[#%]", graid), c("I", "graid"), with = FALSE]

# 3. create an empty stack on which to 'place' embedded clauses
stack <- c()
clauseNumber <- 0
prevBoundary <- 0  # To store the index of the previous boundary marker (if not finished embedded clause)


# 4. initialize a progress bar as a visual aid (this algorithm is a bit slow,
#    let us know if you manage to optimize it a bit...)
progress <- txtProgressBar(min = 0, max = nrow(y), initial = 0,
                           char = "|", width = 80, style = 3)

# 5. loop through all clause boundaries, adding or removing them from the stack
#    depending on their level of embeddedness, and indexing them along the way
for (i in 1:nrow(y)) {
  
  next_boundary <- i + 1
  
  if(grepl("##", y[i, graid])) {
    clauseNumber <- clauseNumber + 1
    stack <- c(clauseNumber)
    prevBoundary <- clauseNumber
    y[i, cID := stack[1]]
  }
  else if(grepl("#", y[i, graid])) {
    clauseNumber <- clauseNumber + 1
    stack <- c(clauseNumber, stack)
    y[i, cID := stack[1]]
    #if next clause boundary not %, update prevBoundary to clauseNumber
    if (!grepl("%", y[next_boundary, graid])) {
      prevBoundary <- clauseNumber
    }
  }
  else if(grepl("%", y[i, graid])) {
    y[i, cID := prevBoundary]
  }
  else {
    y[i, cID := stack[1]]
  }
  
  setTxtProgressBar(progress, i)
}

# 6. merge the clause indices back into the annotation table
mc <- merge(mc, y[, c(1, 3)], by = "I", all = TRUE)
setorder(mc, I)

# 7. copy over the clause indices to all rows in each clause
#    (currently they're only on the clause boundary markers);
#    this also makes clause indices unique *within* each corpus
#    of a corpus (i.e. each corpus starts with clause index 1)

mc <- merge(mc,
            mc[!is.na(cID), .(min_cID = min(cID)), by = "corpus"],
            by = "corpus",
            all = TRUE)
mc[, cID := cID - min_cID + 1]
mc$min_cID <- NULL
setorder(mc, I)
mc[, cID := cID[which(!is.na(cID))], by = cumsum(!is.na(cID))]
```

#### Get Amount of Agreement For Each Language

```{r, warning=FALSE}

# Initialise empty list to store agreement values for each language
agreement_values <- list()

# List of all languages in the corpus
my_languages <- c("english", "persian", "arta", "bora", "cypgreek", "jinghpaw", "kalamang", "mandarin", "matukar", "nafsan", "nkurd", "sanzhi", "sumbawa", "tabasaran", "teop", "tondano", "tulil", "veraa")

# Loop through every language corpus and print amount of agreement
for (language in my_languages){
  
  current_language <- mc[grepl(language, corpus)]
  print(paste("Language:", language))
  print(paste("Number of rows in corpus:", nrow(current_language)))
  
  # Initialize different counters for each step of algorithm
  agreement_graid <- 0
  agreement_gloss_affix <- 0
  agreement_gloss_root <- 0
  
  # Subset all Verbs that are v, vother, cop, aux or -aux and are predicates
  v <- current_language[grepl(".*(\\bv|vother|cop|aux|-aux|=aux).*", graid) & grepl("pred.*", gfunc)]
  
  # Subset arguments that are pronouns or nouns (excluding certain cases)
  arguments <- current_language[grepl("^(?!.*(appos|p2|pred|poss|=|-)).*(pro|np).*(\\:s|\\:a|\\:p).*", graid, perl = TRUE)]
  
  # Subset S, A, and P arguments (NP or free pronoun)
  s <- current_language[grepl("^(?!.*(=|-)).*(pro|np).*(\\:s).*", graid, perl = TRUE)]
  a <- current_language[grepl("^(?!.*(appos|=|-)).*(pro|np).*(\\:a).*", graid, perl = TRUE)]
  p <- current_language[grepl("^(?!.*(p2|pred|poss|=|-)).*(pro|np).*(\\:p).*", graid, perl = TRUE)]
  
  # Subset verbs that have an S, A or P in their clause
  v <- v[v$cID %in% arguments$cID, ]
  print(paste("Number of Verbs:", nrow(v)))
  
  amount_slots <- 0

  # Calculate the total number of possible agreement slots
  for (i in 1:nrow(v)) {
    current_cID <- v$cID[i]
    num_rows <- nrow(arguments[arguments$cID == current_cID, ])
    amount_slots <- amount_slots + num_rows
  }
  print(paste("Total number of possible agreement slots:", amount_slots))
    
  # Loop through all rows in verb subset of current language corpus
  for (v_rows in 1:nrow(v)) {
  
    counter <- 1
    person_counter <- 0
    person_graid_counter <- 0
    
    row_id <- v$I[v_rows]
    current_row <- current_language$graid[current_language$I == (row_id)][1]
    previous_row <- current_language$graid[current_language$I == (row_id - counter)][1]
    previous_row_gloss <- current_language$gloss[current_language$I == (row_id - counter)][1]
    next_row <- current_language$graid[current_language$I == (row_id + counter)][1]
    next_row_gloss <- current_language$gloss[current_language$I == (row_id + counter)][1]
    
    transitivity <- 0
    if ((current_language$cID[current_language$I == row_id]) %in% a$cID){
      transitivity <- 1
    }
    if ((current_language$cID[current_language$I == row_id]) %in% p$cID){
      transitivity <- 1
    }
    if (((current_language$cID[current_language$I == row_id]) %in% p$cID) && ((current_language$cID[current_language$I == row_id]) %in% a$cID)){
      transitivity <- 2
    }
    if ((current_language$cID[current_language$I == row_id]) %in% s$cID){
      transitivity <- 1
    }
    
    # Check previous rows for agreement markers
    while (grepl("[=-]$", previous_row_gloss)) { 
      x <- 0
      if (person_counter < transitivity){
        if (grepl("^(?!.*(appos|p2|pred|poss)).*(\\.\\d).*", previous_row, perl = TRUE)) {
          agreement_graid <- agreement_graid + 1
          x <- 1
          person_counter <- person_counter + 1
          person_graid_counter <- person_graid_counter + 1
        }
        else if (grepl("^(?!.*(appos|p2|pred|poss)).*(\\.h|\\.d|\\_h|\\_d).*", previous_row, perl = TRUE)) {
          agreement_graid <- agreement_graid + 1
          x <- 1
          person_counter <- person_counter + 1
          person_graid_counter <- person_graid_counter + 1
        }
      }
      # Check Gloss tier of current token for agreement marker (Step 2 of Algorithm Procedure)
      if (person_counter < transitivity){
        if (x == 0){
          current_gloss <- current_language$gloss[current_language$I == (row_id - counter)][1]
          current_func <- current_language$gfunc[current_language$I == (row_id + counter)][1]
          if (grepl(".*(\\d).*", current_gloss) && grepl("^(?!.*(TAM|POSS|poss))", current_gloss, perl = TRUE) && grepl("^(?!.*(poss))", current_func, perl = TRUE)) {
            agreement_gloss_affix <- agreement_gloss_affix + 1
            current_I <- current_language$I[current_language$I == (row_id - counter)][1]
            person_boolean <- TRUE
            x <- 1
            person_counter <- person_counter + 1
          }
          else if (grepl(".*(TAM).*(:\\d).*", current_gloss) && grepl("^(?!.*(POSS|poss))", current_gloss, perl = TRUE) && grepl("^(?!.*(poss))", current_func, perl = TRUE)){
            agreement_gloss_affix <- agreement_gloss_affix + 1
            current_I <- current_language$I[current_language$I == (row_id - counter)][1]
            x <- 1
            person_counter <- person_counter + 1
          }
        }
      }
      counter <- counter + 1
      previous_row <- current_language$graid[current_language$I == (row_id - counter)][1]
      previous_row_gloss <- current_language$gloss[current_language$I == (row_id - counter)][1]
    }
    
    counter <- 1  
        
    # Check next row for agreement markers
    if (person_counter < transitivity){
      while (grepl("^[=-]", next_row_gloss)) { 
        x <- 0
        if (person_counter <- transitivity){
          if (grepl("^(?!.*(appos|p2|pred|poss)).*(\\.\\d).*", next_row, perl = TRUE)) {
            agreement_graid <- agreement_graid + 1
            x <- 1
            person_counter <- person_counter + 1
            person_graid_counter <- person_graid_counter + 1
          }
          else if (grepl("^(?!.*(appos|p2|pred|poss)).*(\\.h|\\.d|\\_h|\\_d).*", next_row, perl = TRUE)) {
            agreement_graid <- agreement_graid + 1
            animacy_boolean <- TRUE
            x <- 1
            person_counter <- person_counter + 1
            person_graid_counter <- person_graid_counter + 1
          }
        }
        # Check Gloss tier of current token for agreement marker (Step 2 of Algorithm Procedure)
        if (person_counter < transitivity){
          if (x == 0){
          current_gloss <- current_language$gloss[current_language$I == (row_id + counter)][1]
          current_func <- current_language$gfunc[current_language$I == (row_id + counter)][1]
            if (grepl(".*(\\d).*", current_gloss) && grepl("^(?!.*(TAM|POSS|poss))", current_gloss, perl = TRUE) && grepl("^(?!.*(poss))", current_func, perl = TRUE) ) { ## TAM exclude for Veraa
              agreement_gloss_affix <- agreement_gloss_affix + 1
              current_I <- current_language$I[current_language$I == (row_id - counter)][1]
              x <- 1
              person_counter <- person_counter + 1
            }
            else if (grepl(".*(TAM).*(:\\d).*", current_gloss) && grepl("^(?!.*(TAM|POSS|poss))", current_gloss, perl = TRUE) && grepl("^(?!.*(poss))", current_func, perl = TRUE)){
              agreement_gloss_affix <- agreement_gloss_affix + 1
              current_I <- current_language$I[current_language$I == (row_id - counter)][1]
              x <- 1
              person_counter <- person_counter + 1
            }
          }
        }
        counter <- counter + 1
        next_row <- current_language$graid[current_language$I == (row_id + counter)][1]
        next_row_gloss <- current_language$gloss[current_language$I == (row_id + counter)][1]
      }
    }
        
    #check Gloss tier of current token for agreement marker (Step 3 of Algorithm Procedure)
    if (person_counter < transitivity){
      previous_row <- current_language$graid[current_language$I == (row_id - 1)][1]
      next_row <- current_language$graid[current_language$I == (row_id + 1)][1]
      if (grepl("^(?!.*(-|=)).*", previous_row, perl = TRUE) && grepl("^(?!.*(-|=)).*", next_row, perl = TRUE)){
        if (grepl(".*(\\d).*", v$gloss[v_rows])) {
          matches <- gregexpr("\\d", v$gloss[v_rows])
          number_of_digits <- sum(matches[[1]] != -1)
          if (number_of_digits == 1){
            agreement_gloss_root <- agreement_gloss_root + 1
          }
          if ((number_of_digits == 2) && (person_counter == 0)){
            agreement_gloss_root <- agreement_gloss_root + 2
          }
        }
      }
    }
  }
 
  # Print the agreement counters for the current language
  print(paste("GRAID agreement:", agreement_graid))
  print(paste("GlOSS agreement for Affixes:", agreement_gloss_affix))
  print(paste("GlOSS agreement for Predicate (root):", agreement_gloss_root))
  
  # Calculate and store overall agreement amount for the current language
  syntactical_sum <- agreement_graid + agreement_gloss_affix + agreement_gloss_root
  agreement_overall <- round((syntactical_sum / amount_slots), digits = 4)
  print(paste("Overall Agreement:", agreement_overall))
  agreement_values <- append(agreement_values, agreement_overall)
  cat("\n")
}

```